title: Azure Digital Natives Guide
description: Practical guide for startups moving from MVP to production.
url: "https://azdnguide.com"
baseurl: ""

remote_theme: just-the-docs/just-the-docs

# Use the Kramdown parser in GFM mode to enable task lists
markdown: kramdown
kramdown:
  input: GFM
  task_lists: true

plugins:
  - jekyll-remote-theme
